#include "GameAPI/Game.h"

#include "Mania/ERZ/PhantomMystic.h"
#include "Mania/ERZ/PhantomShinobi.h"
#include "Mania/ERZ/PhantomEgg.h"
#include "Mania/TMZ/CrimsonEye.h"
#include "Mania/MMZ/Gachapandora.h"
#include "Mania/MMZ/EggPistonsMKII.h"
#include "Mania/LRZ/RockDrill.h"
#include "Mania/LRZ/HeavyKing.h"
#include "Mania/LRZ/HeavyRider.h"
#include "Mania/LRZ/DrillerdroidO.h"
#include "Mania/LRZ/Drillerdroid.h"
#include "Mania/OOZ/MegaOctus.h"
#include "Mania/OOZ/MeterDroid.h"
#include "Mania/MSZ/HeavyMystic.h"
#include "Mania/MSZ/DBTower.h"
#include "Mania/MSZ/UberCaterkiller.h"
#include "Mania/HCZ/LaundroMobile.h"
#include "Mania/SSZ/GigaMetal.h"
#include "Mania/SSZ/MetalSonic.h"
#include "Mania/SSZ/HotaruHiWatt.h"
#include "Mania/PGZ/HeavyShinobi.h"
#include "Mania/PGZ/Shiversaw.h"
#include "Mania/FBZ/BigSqueeze.h"
#include "Mania/SPZ/WeatherMobile.h"
#include "Mania/CPZ/AmoebaDroid.h"
#include "Mania/GHZ/DERobot.h"
#include "Mania/GHZ/DDWrecker.h"

#include "Mania/TMZ/FlasherMKII.h"
#include "Mania/TMZ/TurboTurtle.h"
#include "Mania/TMZ/SentryBug.h"
#include "Mania/TMZ/BallHog.h"
#include "Mania/MMZ/PohBee.h"
#include "Mania/MMZ/Scarab.h"
#include "Mania/MMZ/MechaBu.h"
#include "Mania/LRZ/Fireworm.h"
#include "Mania/LRZ/Rexon.h"
#include "Mania/LRZ/Toxomister.h"
#include "Mania/OOZ/Octus.h"
#include "Mania/OOZ/Sol.h"
#include "Mania/OOZ/Aquis.h"
#include "Mania/MSZ/Rattlekiller.h"
#include "Mania/MSZ/RollerMKII.h"
#include "Mania/MSZ/Vultron.h"
#include "Mania/MSZ/Bumpalo.h"
#include "Mania/MSZ/Armadiloid.h"
#include "Mania/MSZ/Cactula.h"
#include "Mania/MSZ/Hatterkiller.h"
#include "Mania/HCZ/TurboSpiker.h"
#include "Mania/HCZ/Buggernaut.h"
#include "Mania/HCZ/MegaChopper.h"
#include "Mania/HCZ/Jawz.h"
#include "Mania/HCZ/Jellygnite.h"
#include "Mania/HCZ/Blastoid.h"
#include "Mania/HCZ/Pointdexter.h"
#include "Mania/SSZ/Kabasira.h"
#include "Mania/SSZ/Dango.h"
#include "Mania/SSZ/Kanabun.h"
#include "Mania/SSZ/HotaruMKII.h"
#include "Mania/SSZ/Hotaru.h"
#include "Mania/PGZ/Woodrow.h"
#include "Mania/PGZ/Dragonfly.h"
#include "Mania/PGZ/IceBomba.h"
#include "Mania/PGZ/JuggleSaw.h"
#include "Mania/FBZ/FBZTrash.h"
#include "Mania/FBZ/Technosqueek.h"
#include "Mania/FBZ/Clucker.h"
#include "Mania/FBZ/Blaster.h"
#include "Mania/SPZ/Shutterbug.h"
#include "Mania/SPZ/Canista.h"
#include "Mania/SPZ/Tubinaut.h"
#include "Mania/SPZ/MicDrop.h"
#include "Mania/CPZ/Grabber.h"
#include "Mania/CPZ/Spiny.h"
#include "Mania/CPZ/CaterkillerJr.h"
#include "Mania/CPZ/Bubbler.h"
#include "Mania/GHZ/Splats.h"
#include "Mania/GHZ/Newtron.h"
#include "Mania/GHZ/Chopper.h"
#include "Mania/GHZ/Crabmeat.h"
#include "Mania/GHZ/Batbrain.h"
#include "Mania/GHZ/Motobug.h"
#include "Mania/GHZ/BuzzBomber.h"


#define REGISTER_ENEMY(name) MOD_REGISTER_OBJ_OVERLOAD(name, NULL, NULL, NULL, NULL, NULL, name##_EnemyInfoHook, NULL, NULL, NULL)

#define HOOK_ENEMY_OBJECTS \
  IMPORT_PUBLIC_FUNC(APICallback_TrackEnemyDefeat); \
  IMPORT_PUBLIC_FUNC(TimeAttackData_TrackEnemyDefeat); \
  \
  OBJ_PHANTOMMYSTIC_SETUP; \
  OBJ_PHANTOMSHINOBI_SETUP; \
  OBJ_PHANTOMEGG_SETUP; \
  OBJ_CRIMSONEYE_SETUP; \
  OBJ_GACHAPANDORA_SETUP; \
  OBJ_EGGPISTONSMKII_SETUP; \
  OBJ_ROCKDRILL_SETUP; \
  OBJ_HEAVYKING_SETUP; \
  OBJ_HEAVYRIDER_SETUP; \
  OBJ_DRILLERDROIDO_SETUP; \
  OBJ_DRILLERDROID_SETUP; \
  OBJ_MEGAOCTUS_SETUP; \
  OBJ_METERDROID_SETUP; \
  OBJ_HEAVYMYSTIC_SETUP; \
  OBJ_DBTOWER_SETUP; \
  OBJ_UBERCATERKILLER_SETUP; \
  OBJ_LAUNDROMOBILE_SETUP; \
  OBJ_METALSONIC_SETUP; \
  OBJ_GIGAMETAL_SETUP; \
  OBJ_HOTARUHIWATT_SETUP; \
  OBJ_HEAVYSHINOBI_SETUP; \
  OBJ_SHIVERSAW_SETUP; \
  OBJ_BIGSQUEEZE_SETUP; \
  OBJ_WEATHERMOBILE_SETUP; \
  OBJ_AMOEBADROID_SETUP; \
  OBJ_DEROBOT_SETUP; \
  OBJ_DDWRECKER_SETUP; \
  \
  OBJ_FLASHERMKII_SETUP; \
  OBJ_TURBOTURTLE_SETUP; \
  OBJ_SENTRYBUG_SETUP; \
  OBJ_BALLHOG_SETUP; \
  OBJ_POHBEE_SETUP; \
  OBJ_SCARAB_SETUP; \
  OBJ_MECHABU_SETUP; \
  OBJ_FIREWORM_SETUP; \
  OBJ_REXON_SETUP; \
  OBJ_TOXOMISTER_SETUP; \
  OBJ_OCTUS_SETUP; \
  OBJ_SOL_SETUP; \
  OBJ_AQUIS_SETUP; \
  OBJ_RATTLEKILLER_SETUP; \
  OBJ_ROLLERMKII_SETUP; \
  OBJ_VULTRON_SETUP; \
  OBJ_BUMPALO_SETUP; \
  OBJ_ARMADILOID_SETUP; \
  OBJ_CACTULA_SETUP; \
  OBJ_HATTERKILLER_SETUP; \
  OBJ_TURBOSPIKER_SETUP; \
  OBJ_BUGGERNAUT_SETUP; \
  OBJ_MEGACHOPPER_SETUP; \
  OBJ_JAWZ_SETUP; \
  OBJ_JELLYGNITE_SETUP; \
  OBJ_BLASTOID_SETUP; \
  OBJ_POINTDEXTER_SETUP; \
  OBJ_KABASIRA_SETUP; \
  OBJ_DANGO_SETUP; \
  OBJ_KANABUN_SETUP; \
  OBJ_HOTARUMKII_SETUP; \
  OBJ_HOTARU_SETUP; \
  OBJ_WOODROW_SETUP; \
  OBJ_DRAGONFLY_SETUP; \
  OBJ_ICEBOMBA_SETUP; \
  OBJ_JUGGLESAW_SETUP; \
  OBJ_FBZTRASH_SETUP; \
  OBJ_TECHNOSQUEEK_SETUP; \
  OBJ_CLUCKER_SETUP; \
  OBJ_BLASTER_SETUP; \
  OBJ_CANISTA_SETUP; \
  OBJ_TUBINAUT_SETUP; \
  OBJ_SHUTTERBUG_SETUP; \
  OBJ_MICDROP_SETUP; \
  OBJ_SPINY_SETUP; \
  OBJ_GRABBER_SETUP; \
  OBJ_CATERKILLERJR_SETUP; \
  OBJ_BUBBLER_SETUP; \
  OBJ_SPLATS_SETUP; \
  OBJ_NEWTRON_SETUP; \
  OBJ_CHOPPER_SETUP; \
  OBJ_CRABMEAT_SETUP; \
  OBJ_BATBRAIN_SETUP; \
  OBJ_MOTOBUG_SETUP; \
  OBJ_BUZZBOMBER_SETUP
